run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis checks
    - unused        # Check for unused constants, variables, functions
    - gofmt         # Check code formatting
    - goimports     # Check import formatting
    - misspell      # Check for misspelled words
    - revive        # Fast, configurable, extensible linter
    - gosec         # Security checks
    - unconvert     # Remove unnecessary type conversions
    - gocritic      # Opinionated Go linter
    - unparam       # Find unused function parameters

  disable:
    - exhaustive    # Too strict for switches
    - cyclop        # Complex cyclomatic complexity checks

linters-settings:
  errcheck:
    check-type-assertions: false  # Type assertions in heap operations are safe
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow  # Too many false positives
      - fieldalignment  # Memory optimization, not critical for correctness
      - unusedwrite  # Common in test code

  revive:
    severity: warning
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: duplicated-imports
      - name: modifies-value-receiver

  gosec:
    excludes:
      - G404  # Use of weak random number generator - we use math/rand for simulation

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentedOutCode
      - hugeParam
      - builtinShadow  # min/max parameter names are acceptable
      - paramTypeCombine  # Explicit types improve readability

issues:
  exclude-dirs:
    - gen
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - unparam
        - gocritic
        - errcheck

    # Exclude shadow checking on the variable named err
    - text: "shadow: declaration of \"err\""
      linters:
        - govet

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
